const menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open)});
const reel=document.querySelector('.hero-reel');if(reel&&matchMedia('(prefers-reduced-motion: reduce)').matches){reel.pause();reel.removeAttribute('autoplay')}
const dialog=document.querySelector('#gallery-dialog');let current=[],index=0,project=null;
function showItem(){const item=current[index],content=dialog.querySelector('.dialog-content');content.replaceChildren();const media=document.createElement(item.type==='video'?'video':'img');media.src=item.src;if(item.type==='video'){media.controls=true;media.playsInline=true;media.preload='metadata'}else media.alt=item.alt||project.title;content.append(media);dialog.querySelector('.dialog-title').textContent=project.title;dialog.querySelector('.dialog-description').textContent=project.desc||project.subtitle||'';dialog.querySelector('.count').textContent=`${index+1} / ${current.length}`;dialog.querySelectorAll('[data-nav]').forEach(x=>x.hidden=current.length<2)}
function openGallery(id,start=0){project=window.portfolioData.find(x=>x.id===id);if(!project)return;current=project.media;index=start;showItem();dialog.showModal();document.body.style.overflow='hidden'}
document.querySelectorAll('[data-project]').forEach(btn=>btn.addEventListener('click',()=>openGallery(btn.dataset.project,Number(btn.dataset.index||0))));
dialog?.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>{dialog.querySelector('video')?.pause();dialog.querySelector('.dialog-content').replaceChildren();document.body.style.overflow=''});
dialog?.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
function step(d){index=(index+d+current.length)%current.length;dialog.querySelector('video')?.pause();showItem()}
dialog?.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>step(Number(btn.dataset.nav))));dialog?.addEventListener('keydown',event=>{if(event.target.tagName==='VIDEO')return;if(event.key==='ArrowRight'){event.preventDefault();step(1)}if(event.key==='ArrowLeft'){event.preventDefault();step(-1)}});
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===btn)));document.querySelectorAll('[data-category]').forEach(card=>card.hidden=btn.dataset.filter!=='all'&&card.dataset.category!==btn.dataset.filter)}));
